name: amyos
description: https://ublue.it/making-your-own/

base-image: ghcr.io/ublue-os/silverblue-main
image-version: 39

modules:
  - type: files
    files:
      - usr: /usr

  - type: rpm-ostree
    repos:
      - https://raw.githubusercontent.com/astrovm/amyos/live/repos/vscode.repo
    install:
      - alacritty
      - android-tools
      - aria2
      - binutils
      - binutils-devel
      - code
      - croc
      - diffstat
      - doxygen
      - emacs
      - firewall-config
      - gcc
      - gcc-c++
      - gettext
      - gparted
      - kdeconnectd
      - kitty
      - langpacks-en
      - libvirt-daemon-config-network
      - libvirt-daemon-kvm
      - lld
      - lm_sensors
      - neofetch
      - neovim
      - net-tools
      - openssl-devel
      - p7zip
      - p7zip-plugins
      - patch
      - patchutils
      - python3-pip
      - qemu-kvm
      - subversion
      - systemtap
      - tmux
      - util-linux-user
      - virt-install
      - virt-manager
      - virt-viewer
      - wireguard-tools
      - zsh
    remove:
      - firefox
      - firefox-langpacks

  - type: default-flatpaks
    notify: true
    system:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      install:
        - com.bitwarden.desktop
        - com.calibre_ebook.calibre
        - com.github.k4zmu2a.spacecadetpinball
        - com.github.micahflee.torbrowser-launcher
        - com.github.wwmm.easyeffects
        - com.stremio.Stremio
        - io.github.hakuneko.HakuNeko
        - io.gitlab.librewolf-community
        - net.lutris.Lutris
        - net.pcsx2.PCSX2
        - network.loki.Session
        - org.audacityteam.Audacity
        - org.duckstation.DuckStation
        - org.gimp.GIMP
        - org.kde.kdenlive
        - org.qbittorrent.qBittorrent
        - org.telegram.desktop
        - org.videolan.VLC
        - org.yuzu_emu.yuzu
      repo-url: oci+https://registry.fedoraproject.org
      repo-name: fedora
      install:
        - com.ylsoftware.qmmp.Qmmp

  - type: script
    scripts:
      - signing.sh
